=== tszylkiewicz/PKCK/definition.dtd
<!ELEMENT moviesCollection (movies, directors)>

<!ELEMENT movies (movie*)>
<!ELEMENT movie (title,director+,genre+,release_date,duration,production)>
<!ATTLIST movie MovieID ID #REQUIRED 
				DirectorID IDREF #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT release_date (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT production (#PCDATA)>

<!ELEMENT directors (person*)>
<!ELEMENT director (firstname, lastname, birth_date, birth_city)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT birth_date (#PCDATA)>
<!ELEMENT birth_city (#PCDATA)>

=== tszylkiewicz/PKCK/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css" ?>
<!DOCTYPE note SYSTEM "definition.dtd">
<movies>
	<movie>
		<title>Kapitan Marvel</title>
		<director>Anna Boden</director>
		<genre>Action, Sci-Fi</genre>
		<release_date>06-03-2019</release_date>
		<duration>124</duration>
		<production>USA</production>
	</movie>
	<movie>
		<title>Iron Man</title>
		<director>Jon Favreau</director>
		<genre>Action, Sci-Fi</genre>
		<release_date>14-04-2008</release_date>
		<duration>126</duration>
		<production>USA</production>
	</movie>
	<movie>
		<title>Alien Coventant</title>
		<director>Ridley Scott</director>
		<genre>Horror, Sci-Fi</genre>
		<release_date>04-05-2017</release_date>
		<duration>122</duration>
		<production>USA, United Kingdom</production>
	</movie>
	<movie>
		<title>Deadpool</title>
		<director>Jon Favreau</director>
		<genre>Action, Comedy, Sci-Fi</genre>
		<release_date>21-01-2016</release_date>
		<duration>108</duration>
		<production>USA</production>
	</movie>
	<movie>
		<title>Suicide Squad</title>
		<director>David Ayer</director>
		<genre>Action, Sci-Fi</genre>
		<release_date>05-06-2016</release_date>
		<duration>123</duration>
		<production>USA, Canada</production>
	</movie>
</movies>
